fix(tf): change s3 endpoint settings to remediate timestamp error
Error:
	InvalidParameterValueException: TimestampColumnName cannot be an
	empty string.

Resolved by adding timestamp_column_name = "TIMESTAMP”
(This seems to be required for Parquet data type but not CSV)